### PR TITLE
Choropleth

### PR DESCRIPTION
**Pull request by michaeljpeake**
Based on what @michaeljpeake and @EddyLane have discussed below, here’s the work that I think is remaining on this for it to be ready to launch (there are nice-to-haves such as improving the legend and adding tooltips, but I’m ignoring them for now):

- [ ] Update to use live API endpoints, see below (remove mock data JSON files)
- [ ] Refactor the map JavaScript from this page and the ‘Leading party for each constituency’ page into a shared module
- [ ] Sort out the colour scales - there’s a mix of styles used at the moment.
  - “It would be nice if they were all like Labour’s; however, I found that the different shades are hard to spot when using that with blue, green and especially yellow.” - @michaeljpeake
- [ ] Extract colours into the site `config.js` file so whatever colours eventually get decided on, they can be used elsewhere in the site
- [ ] Some explanation of what the % means should be added for the legend
- [ ] Update the JSDoc blocks - some of the `@params` are invalid
- [ ] Remove commented out code

I’m unsure about the fact that for each party the percentage ranges are different - wondering if this is going to be misleading, but would appreciate others thoughts on this.

As mentioned in the issue for this (https://github.com/voteforpolicies/data-website/issues/20), the required API endpoints now exist:

`GET /parties/{party_slug}/constituencies/results.json` - List votes count and percentage for a specific party in all constituencies

\- @simonplend

-----

*Original description by @michaeljpeake:*

This PR adds a choropleth map to the 'constituency' folder.

As the API is not yet able to provide the necessary json, mock files have been added to show functionality. For the same reason, a link has not been included in the index file.

Both choropleths.html and choropleths.js are built from the leading-party page. There is likely some redundant code and definitely some 'tidying up' to be done.

Functions already built:
* Map update when a new party is selected
* Legend update when a new party is selected

Priority fixes/features to add:
* API update
* Legend could be improved; needs some visual love
* Tooltip to show individual constituency percentage (potentially listing all parties - though likely to be too slow)
* If tooltip is added, zoom function will be required to select small constituencies (e.g. London boroughs)

### CODE REVIEW

**Comment by michaeljpeake** [comment]
Some constituencies that you might expect to be coloured are not. This is because my mock files are missing some data. It shouldn't be an issue with the live version.

**Comment by michaeljpeake** [comment]
Two further thoughts:

* The colour scales are very much up for debate. There's a mix of styles used at the moment. I would be nice is they were all like Labour's; however, I found that the different shades are hard to spot when using that with blue, green and especially yellow.
* Some explanation of what the % means should be added about the tables. Something to add for the live version.

**Comment by simonplend** [comment]
For issue https://github.com/voteforpolicies/data-website/issues/20

@michaeljpeake Looks great! Going to try it out and will be in touch by the end of the week.

**Comment by EddyLane** [comment]
Hi Michael,

First off, great to see some more people contributing to the website!

I've a couple of suggestions about your PR, I hope you don't take any of these disparagingly as that is not the intension! I just want to make sure the codebase remains easy to build on for us all :)

* Your **choropleths.js** file is an enhanced version of the **map.js** file that is used on the leading-parties view. Can I suggest that you extract the Map into a separate component/javascript file that can be used on both of the leading-parties and the choropleth pages?

* Can we try and make sure that we keep JSDoc blocks as up to date, I see that some of the JSDoc @params are now invalid.

* Could we potentially extract [these colours](https://github.com/michaeljpeake/data-website/commit/b8dc5768c21d4f3caa16c158896300539db336ed#diff-6575cd73aad8cf3039c95a2b08848848R68) into the **config.js** file so whatever colours eventually get decided on, they can be used elsewhere in the site? /cc @simonplend 

* Can I suggest that [commented out code](https://github.com/michaeljpeake/data-website/commit/b8dc5768c21d4f3caa16c158896300539db336ed#diff-6575cd73aad8cf3039c95a2b08848848R41) is not committed as this tends to lead to a bit of an elephants graveyard.

Thanks Michael. Again, great to see new people, and welcome to start a discussion about any of these points with yourself and @simonplend and anyone who is planning to contribute.

Thanks,

-Eddy

**Comment by michaeljpeake** [comment]
Hi Eddy

Thanks for all the comments. Not disparaging at all. This is my first experience with D3 so all comments are welcome.

Aware that much of the code can be tidied up. I wanted to get the PR up though so Simon could see the thing working while I did the loose ends (removing commented and redundant code).

Should the extracted of the map for the leading-parties and choropleth pages perhaps be a separate PR?

**Comment by EddyLane** [comment]
Hi Again,

I'm personally of the opinion that the map abstraction should be part of this PR as otherwise the master branch could be left in a state of limbo before the next PR is merged, but welcome to hear others opinions.

**Comment by simonplend** [comment]
This choropleth has now been integrated into the Constituency Explorer PR: https://github.com/voteforpolicies/data-website/pull/50

Thanks @michaeljpeake!

**Pull request closed without merging**
