### PR TITLE
Feature/map improvements

### PR DESCRIPTION
**Pull request by EddyLane**
This PR adds the following functionality to the leading-parties page:

- Click table to zoom in/zoom out of a particular constituency.
- Click outside of the map to zoom out of the map if zoomed in.

It also improves the performance by doing two things:

- The un-coloured map has been pre-rendered and saved to an SVG, which is then hooked up to D3.
- The TopoJSON has been simplified

### CODE REVIEW

**Comment by EddyLane** [comment]
This issue also resolves #1 (not in the nicest way possible, but in a way which I think will do as this is the only case of a special character in a constituency)

**Comment by simonplend** [comment]
@EddyLane I've got a few questions, but this looks really good. Much better UX and performance. Will try and get this released tomorrow.

**Comment by EddyLane** [comment]
Cool, what questions do you have mate?

**Comment by simonplend** [comment]
@EddyLane Interested to know, how did you simplify the TopoJSON? It's something I never got around to investigating before.

**Comment by EddyLane** [comment]
Ah, I tried to use the topojson npm module with the -s flag but I had more success with this thing: http://www.mapshaper.org/. The most performance gains came from having the svg file pre-loaded though.

**Comment by simonplend** [comment]
@EddyLane That's a really neat tool. Can you remember which settings you used for the simplified file in this PR? Would just be handy for future reference.

**Comment by EddyLane** [comment]
@simonplend Pretty sure it was **Visvalingam / weighted area** and just adjusted sliders, can't remember exact numbers i'm afraid.

**Comment by simonplend** [comment]
Reviewed :+1:

**Pull request merged**
