### PR TITLE
Restructuring of the site to use DocPad

### PR DESCRIPTION
**Pull request by simonplend**
For issue https://github.com/voteforpolicies/data-website/issues/5, https://github.com/voteforpolicies/data-website/issues/36, https://github.com/voteforpolicies/data-website/issues/38 and partly resolves https://github.com/voteforpolicies/data-website/issues/7.

- Layout template uses ECO (Embedded CoffeeScript) as it is the default template engine for DocPad so it exposes DocPad view helpers by default. Up for discussion whether we should use ECO for all templates - we could use a different template engine such as Handlebars, for example.
- Google Analytics tracking code - now conditional, will only show when environment is ‘production’
- JavaScript files can be specified in the meta for each page (basic implementation)

**TODO**

- [x] Set up routing
- [x] Migrate ‘Leading parties’ page
- [x] Merge in master once Browserify PR has been merged (https://github.com/voteforpolicies/data-website/pull/35)
- [x] Resolve merge conflicts
- [x] Migrate 'Country results' page
- [x] Migrate 'Constituency results' page
- [x] Add steps to setup DocPad to a README
- [x] [Replicate primary navigation from the main site](https://github.com/voteforpolicies/data-website/issues/36)
- [x] Add 'use strict' to top of JS files
- [x] Generate a cache busting version of `build.js` in production so that we can set decent cache headers e.g. `build_76d663c2420825435ffbe8eaf7dc64c6.js`

### CODE REVIEW

**Comment by simonplend** [comment]
I'm going to convert the 'Leading party for each constituency' page this evening as it's a bit more meaty than the home page for the data site, but let me know your thoughts so far!

/cc @ryanhyslop @EddyLane

**Comment by simonplend** [comment]
If everyone's happy with this, I'll finish templating the rest of the site tomorrow evening.

/cc @ryanhyslop @EddyLane

**Comment by ryanhyslop** [comment]
Just checked out the PR locally, docpad looks like it'll do the job.

Its a bit of a shame about ECO by default ( from my POV ), but looking at converting the helpers for something a bit more 'mainstream' like handlebars looks a bit of a mission (https://github.com/docpad/docpad-plugin-handlebars/issues/2) so will do for now at least.

If you can get the bare minimum done here Simon just to replicate what we've got on master, even if its not perfect then we can all jump in and start adding the appropriate bits, additional tidying up & adding some documentation to the readme.

Just a heads up anyone else that checks this out 

```
npm install -g docpad
```

```
docpad install eco
```

```
dockpad run
```

**Comment by simonplend** [comment]
Great, it shouldn't be too much work to migrate the other two pages.

Yeah, I agree about ECO by default not being the ideal and I ran across the same issue for exposing view helpers for other template engines like Handlebars. Like you say though, it should do for now and we can improve on this if we need to.

Progress!

**Comment by simonplend** [comment]
@ryanhyslop @EddyLane Please give this a review if you can - keen to get it merged and make a release tonight! Will be another tidy one: https://github.com/voteforpolicies/data-website/issues?q=is%3Aopen+is%3Aissue+label%3Anext-release

**Comment by simonplend** [comment]
I've tried disabling the assets plugin in development as we don't need it until the site is built for production, however it causes an undefined function error, caused by the `asset()` function not being available to the layout ECO template as the plugin is disabled. I'm not sure of a way around this. This is how you disable the plugin in development though:

```js
var docpadConfig = {
    plugins: {
        cleanurls: {
            enabled: true
        },
        assets: {
            enabled: true,
            retainName: 'yes'
            environments: {
                development: {
                    enabled: false
                }
            }
        }
    }
};
```

**Pull request merged**
